### ISSUE TITLE
Generate a new dataset?

### ISSUE THREAD

**Issue by vdidonato** [twitter/SentenTree#3]
Is there in the repository any code that given a set of tweets produces a suitable dataset?
I mean a dataset in the format  [{ id, text, count }].

I could do it manually but how should I compute count for each tweet? Is it the number of retweets? What is it exactly?

**Comment by kristw** [comment]
The preprocessing is not in the scope of this library. It was designed to support any text and not limited to Tweets. We believe the users of this library should be able to convert from their own data source into this simple format by themselves.

The `count` can be retweets, likes, or any number you want it to be. This is used to determine how important that Tweet is, and affect the word size.
